### ISSUE TITLE
nacos-client 2.2.1的auth、query和configChange问题

### ISSUE THREAD

**Issue by zzyandzzy** [heqingpan/rnacos#14]
因为我们项目使用的nacos版本是2.2.1，目前遇到以下一些问题：

1、nacos 2.2.1 auth的url为：/nacos/v1/auth/users/login，以前的是（/nacos/v1/auth/login）

2、rpc调用query的问题，因为项目本地开发使用dev环境，nacos在查询不到配置的时候会默认查询dev后缀的配置，如：data-id为gateway.yml查询不到就会去查询gateway-dev.yml，但前提是返回的error_code为300，nacos相关源代码：
```java
// ~/.m2/repository/com/alibaba/nacos/nacos-client/2.2.1/nacos-client-2.2.1-sources.jar!/com/alibaba/nacos/client/config/impl/ClientWorker.java#queryConfig
 if (response.isSuccess()) {
    // ...
    return configResponse;
} else if (response.getErrorCode() == ConfigQueryResponse.CONFIG_NOT_FOUND) {
    // ConfigQueryResponse.CONFIG_NOT_FOUND = 300，尝试重新查询dev环境
    LocalConfigInfoProcessor.saveSnapshot(this.getName(), dataId, group, tenant, null);
    LocalEncryptedDataKeyProcessor.saveEncryptDataKeySnapshot(agent.getName(), dataId, group, tenant, null);
    return configResponse;
}
```

3、我在修改了以上两处bug后又遇到configChange不为空导致无限查询的问题，问题代码在于这里：

```java
// ~/.m2/repository/com/alibaba/nacos/nacos-client/2.2.1/nacos-client-2.2.1-sources.jar!/com/alibaba/nacos/client/config/impl/ClientWorker.java#executeConfigListen

public void executeConfigListen() {
    // ...
    RpcClient rpcClient = ensureRpcClient(taskId);
    ConfigChangeBatchListenResponse configChangeBatchListenResponse = (ConfigChangeBatchListenResponse) requestProxy(rpcClient, configChangeListenRequest);
    if (configChangeBatchListenResponse.isSuccess()) {
    Set<String> changeKeys = new HashSet<>();
    //handle changed keys,notify listener
    // 问题出在这儿，当配置改变的时候，changedConfigs才不为空，但是面前rnacos的rpc是查询到有该配置就返回，所以造成了bug
    if (!CollectionUtils.isEmpty(configChangeBatchListenResponse.getChangedConfigs())) {
        // ...
    }
}
```
目前我通过注释config_change_batch_listen.rs里面直接返回空值修复改bug，后续肯定是要加上缓存机制完善代码的。

**Comment by zzyandzzy** [comment]
提交了pr，修复了上面说的1、2的bug，但是3的bug我的处理方式不是很合适，所以没有提pr

**Comment by heqingpan** [comment]
收到。
我回去确认这个场景问题后再解决。

**Comment by heqingpan** [comment]
最新版本v0.3.3已修复

**Comment by zzyandzzy** [comment]
我测试了一下，第三个bug还是没有修复，我这里有个最小的测试案例。
[nacos-gateway-test](https://github.com/zzyandzzy/nacos-gateway-test)，

nacos配置, config id: `gateway-test.yml`, group: `DEFAULT_GROUP`
```yml
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-headers: "*"
            # 半个月内都允许
            max-age: 1296000
            # 测试环境，全部允许
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
              - DELETE
      discovery:
        locator:
          enabled: true
```

可以测试一下，原因上面已经说了，
```java
public void executeConfigListen() {
    // ...
    RpcClient rpcClient = ensureRpcClient(taskId);
    ConfigChangeBatchListenResponse configChangeBatchListenResponse = (ConfigChangeBatchListenResponse) requestProxy(rpcClient, configChangeListenRequest);
    if (configChangeBatchListenResponse.isSuccess()) {
    Set<String> changeKeys = new HashSet<>();
    //handle changed keys,notify listener
    // 问题出在这儿，当配置改变的时候，changedConfigs才不为空，但是面前rnacos的rpc是查询到有该配置就返回，所以造成了bug
    if (!CollectionUtils.isEmpty(configChangeBatchListenResponse.getChangedConfigs())) {
        // ...
    }
}
```
目前我是通过注释掉`src/grpc/handler/config_change_batch_listen.rs`的返回来防止这个bug，代码如下：
```rust
#[async_trait]
impl PayloadHandler for ConfigChangeBatchListenRequestHandler {
    async fn handle(
        &self,
        request_payload: crate::grpc::nacos_proto::Payload,
        request_meta: crate::grpc::RequestMeta,
    ) -> anyhow::Result<Payload> {
        // ...
        match self.app_data.config_addr.send(cmd).await {
            Ok(res) => {
                let r: ConfigResult = res.unwrap();
                match r {
                    // 注释掉防止changeConfig不为空导致的bug
                    // ConfigResult::ChangeKey(keys) => {
                    //     response.result_code = SUCCESS_CODE;
                    //     for key in keys {
                    //         let obj = ConfigContext {
                    //             data_id: key.data_id,
                    //             group: key.group,
                    //             tenant: key.tenant,
                    //         };
                    //         response.changed_configs.push(obj);
                    //     }
                    // }
                    _ => {
                        response.result_code = SUCCESS_CODE;
                    }
                }
                Ok(PayloadUtils::build_payload(
                    "ConfigChangeBatchListenResponse",
                    serde_json::to_string(&response)?,
                ))
            }
    }
}
```
